name: My Work
on:
  # Run manually
  workflow_dispatch:

jobs:
  my_work:
    name: "My Work"
    runs-on: ubuntu-latest
    steps:
      - name: Run my action
        uses: inkblotty/my-work-action@feat/use-absolute-url-for-prs
        with:
          owner: inkblotty
          repo: daily-update-action
          secondary_prs_label: "test"
          queried_repos: "daily-update-action,my-work-action,khiga8/github-a11y"
          usernames: inkblotty
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
